### ISSUE TITLE
[MFWebCamToFile] Webcam resolution

### ISSUE THREAD

**Issue by OgreTransporter** [sipsorcery/mediafoundationsamples#4]
Hi,

I've tried to Change the Webcam resolution by calling SetDeviceFormat from https://msdn.microsoft.com/en-us/library/windows/desktop/ff485858(v=vs.85).aspx after MFCreateSourceReaderFromMediaSource but it's not working. How can I change the Resolution to 1280x720?

**Comment by sipsorcery** [comment]
The `MFWebCamToFile` sample now has defines to set the frame size and resolution.

For large frame sizes you'll probably have to mess around with the [H264 media type](https://docs.microsoft.com/en-us/windows/win32/medfound/h-264-video-encoder) attributes. On my machine the H264 encoder is rejecting a frame size of 1600x1200. I suspect it's because some buffer somewhere is exceeding a limit and the bitrate or some other parameter needs to be reduced.
