### ISSUE TITLE
MFVideoEVR displays no video

### ISSUE THREAD

**Issue by sdaly2324** [sipsorcery/mediafoundationsamples#5]
I changed CreateObjectFromURL to use an mp4 file on my machine.
I get no errors, just:
Attempting to write sample to stream sink.
Attempting to write sample to stream sink.
Attempting to write sample to stream sink.
NO VIDEO IS DISPLAYED IN THE HWND _hwnd!!!

**Comment by sipsorcery** [comment]
It's been a looong time since I've looked at Media Foundation. One of the trickiest things when opening media was to get the encoding parameters correct. In theory you'd think it would just work for media files as the encoding parameters are generally somewhere in the file. But MF always seemed to want them manually set and when you're talking about H.264 video and AAC audio it can get head wrecking.

So sorry I can't be much help to you.

**Comment by iamrameshkumar** [comment]
Anyone got it working? I'm new to this and I can't find a code sample in the internet that works out of the box. Any help would be appreciated.

**Comment by sipsorcery** [comment]
That sample is now fixed.
